/** @format */

//  auth

const AUTH_KEY = "AUTH";

export const LOGIN = `${AUTH_KEY}/LOGIN`;
export const LOGIN_START = `${AUTH_KEY}/LOGIN_START`;
export const LOGIN_SUCCESS = `${AUTH_KEY}/LOGIN_SUCCESS`;
export const LOGIN_FAILED = `${AUTH_KEY}/LOGIN_FAILED`;

export const SIGN_UP = `${AUTH_KEY}/SIGN_UP`;
export const SIGN_UP_START = `${AUTH_KEY}/SIGN_UP_START`;
export const SIGN_UP_SUCCESS = `${AUTH_KEY}/SIGN_UP_SUCCESS`;
export const SIGN_UP_FAILED = `${AUTH_KEY}/SIGN_UP_FAILED`;

export const LOGOUT = `${AUTH_KEY}/LOGOUT`;

// ui
const UI_KEY = "UI";

export const ADD_NOTI = `${UI_KEY}/ADD_NOTI`;
export const REMOVE_NOTI = `${UI_KEY}/REMOVE_NOTI`;
export const SHOW_SIDEBAR = `${UI_KEY}/SHOW_SIDEBAR`;
export const HIDE_SIDEBAR = `${UI_KEY}/HIDE_SIDEBAR`;

// user

const USER_KEY = "USER";

export const GET_USER_PROFILE = `${USER_KEY}/GET_USER_PROFILE`;
export const GET_USER_PROFILE_START = `${USER_KEY}/GET_USER_PROFILE_START`;
export const GET_USER_PROFILE_SUCCESS = `${USER_KEY}/GET_USER_PROFILE_SUCCESS`;
export const GET_USER_PROFILE_FAILED = `${USER_KEY}/GET_USER_PROFILE_FAILED`;

export const EDIT_USER_PROFILE = `${USER_KEY}/EDIT_USER_PROFILE`;
export const EDIT_USER_PROFILE_START = `${USER_KEY}/EDIT_USER_PROFILE_START`;
export const EDIT_USER_PROFILE_SUCCESS = `${USER_KEY}/EDIT_USER_PROFILE_SUCCESS`;
export const EDIT_USER_PROFILE_FAILED = `${USER_KEY}/EDIT_USER_PROFILE_FAILED`;

// admin

const ADMIN_KEY = "ADMIN";

export const GET_LIST_MANAGER = `${ADMIN_KEY}/GET_LIST_MANAGER`;
export const GET_LIST_MANAGER_START = `${ADMIN_KEY}/GET_LIST_MANAGER_START`;
export const GET_LIST_MANAGER_SUCCESS = `${ADMIN_KEY}/GET_LIST_MANAGER_SUCCESS`;
export const GET_LIST_MANAGER_FAILED = `${ADMIN_KEY}/GET_LIST_MANAGER_FAILED`;

export const GET_LIST_STAFF = `${ADMIN_KEY}/GET_LIST_STAFF`;
export const GET_LIST_STAFF_START = `${ADMIN_KEY}/GET_LIST_STAFF_START`;
export const GET_LIST_STAFF_SUCCESS = `${ADMIN_KEY}/GET_LIST_STAFF_SUCCESS`;
export const GET_LIST_STAFF_FAILED = `${ADMIN_KEY}/GET_LIST_STAFF_FAILED`;

export const CREATE_ACCOUNT = `${ADMIN_KEY}/CREATE_ACCOUNT`;
export const CREATE_ACCOUNT_START = `${ADMIN_KEY}/CREATE_ACCOUNT_START`;
export const CREATE_ACCOUNT_SUCCESS = `${ADMIN_KEY}/CREATE_ACCOUNT_SUCCESS`;
export const CREATE_ACCOUNT_FAILED = `${ADMIN_KEY}/CREATE_ACCOUNT_FAILED`;
export const RESET_CREATE_ACCOUNT_STATE = `${ADMIN_KEY}/RESET_CREATE_ACCOUNT_STATE`;
export const REMOVE_ACCOUNT_FROM_STATE = `${ADMIN_KEY}/REMOVE_ACCOUNT_FROM_STATE`;

export const UPDATE_ACCOUNT_INFO = `${ADMIN_KEY}/UPDATE_ACCOUNT_INFO`;
export const UPDATE_ACCOUNT_INFO_START = `${ADMIN_KEY}/UPDATE_ACCOUNT_INFO_START`;
export const UPDATE_ACCOUNT_INFO_SUCCESS = `${ADMIN_KEY}/UPDATE_ACCOUNT_INFO_SUCCESS`;
export const UPDATE_ACCOUNT_INFO_FAILED = `${ADMIN_KEY}/UPDATE_ACCOUNT_INFO_FAILED`;
export const RESET_UPDATE_ACCOUNT_STATE = `${ADMIN_KEY}/RESET_UPDATE_ACCOUNT_STATE`;

// manager

// admin

const MANAGER_KEY = "MANAGER";

export const GET_LIST_CURRENT_FILM = `${MANAGER_KEY}/GET_LIST_CURRENT_FILM`;
export const GET_LIST_CURRENT_FILM_START = `${MANAGER_KEY}/GET_LIST_CURRENT_FILM_START`;
export const GET_LIST_CURRENT_FILM_SUCCESS = `${MANAGER_KEY}/GET_LIST_CURRENT_FILM_SUCCESS`;
export const GET_LIST_CURRENT_FILM_FAILED = `${MANAGER_KEY}/GET_LIST_CURRENT_FILM_FAILED`;

export const CREATE_NEW_FILM = `${MANAGER_KEY}/CREATE_NEW_FILM`;
export const CREATE_NEW_FILM_START = `${MANAGER_KEY}/CREATE_NEW_FILM_START`;
export const CREATE_NEW_FILM_SUCCESS = `${MANAGER_KEY}/CREATE_NEW_FILM_SUCCESS`;
export const CREATE_NEW_FILM_FAILED = `${MANAGER_KEY}/CREATE_NEW_FILM_FAILED`;
export const RESET_CREATE_FILM_STATE = `${ADMIN_KEY}/RESET_CREATE_FILM_STATE`;

export const GET_LIST_COMING_FILM = `${MANAGER_KEY}/GET_LIST_COMING_FILM`;
export const GET_LIST_COMING_FILM_START = `${MANAGER_KEY}/GET_LIST_COMING_FILM_START`;
export const GET_LIST_COMING_FILM_SUCCESS = `${MANAGER_KEY}/GET_LIST_COMING_FILM_SUCCESS`;
export const GET_LIST_COMING_FILM_FAILED = `${MANAGER_KEY}/GET_LIST_COMING_FILM_FAILED`;

export const UPDATE_FILM_INFO = `${MANAGER_KEY}/UPDATE_FILM_INFO`;
export const UPDATE_FILM_INFO_START = `${MANAGER_KEY}/UPDATE_FILM_INFO_START`;
export const UPDATE_FILM_INFO_SUCCESS = `${MANAGER_KEY}/UPDATE_FILM_INFO_SUCCESS`;
export const UPDATE_FILM_INFO_FAILED = `${MANAGER_KEY}/UPDATE_FILM_INFO_FAILED`;

export const REMOVE_FILM_FROM_STATE = `${ADMIN_KEY}/REMOVE_FILM_FROM_STATE`;

export const GET_LIST_ROOM = `${MANAGER_KEY}/GET_LIST_ROOM`;
export const GET_LIST_ROOM_START = `${MANAGER_KEY}/GET_LIST_ROOM_START`;
export const GET_LIST_ROOM_SUCCESS = `${MANAGER_KEY}/GET_LIST_ROOM_SUCCESS`;
export const GET_LIST_ROOM_FAILED = `${MANAGER_KEY}/GET_LIST_ROOM_FAILED`;
export const REMOVE_ROOM_FROM_STATE = `${ADMIN_KEY}/REMOVE_ROOM_FROM_STATE`;

export const CREATE_ROOM = `${MANAGER_KEY}/CREATE_ROOM`;
export const CREATE_ROOM_START = `${MANAGER_KEY}/CREATE_ROOM_START`;
export const CREATE_ROOM_SUCCESS = `${MANAGER_KEY}/CREATE_ROOM_SUCCESS`;
export const CREATE_ROOM_FAILED = `${MANAGER_KEY}/CREATE_ROOM_FAILED`;
export const RESET_CREATE_ROOM_STATE = `${MANAGER_KEY}/RESET_CREATE_ROOM_STATE`;

export const UPDATE_ROOM_INFO = `${MANAGER_KEY}/UPDATE_ROOM_INFO`;
export const UPDATE_ROOM_INFO_START = `${MANAGER_KEY}/UPDATE_ROOM_INFO_START`;
export const UPDATE_ROOM_INFO_SUCCESS = `${MANAGER_KEY}/UPDATE_ROOM_INFO_SUCCESS`;
export const UPDATE_ROOM_INFO_FAILED = `${MANAGER_KEY}/UPDATE_ROOM_INFO_FAILED`;

export const GET_LIST_SLOT = `${MANAGER_KEY}/GET_LIST_SLOT`;
export const GET_LIST_SLOT_START = `${MANAGER_KEY}/GET_LIST_SLOT_START`;
export const GET_LIST_SLOT_SUCCESS = `${MANAGER_KEY}/GET_LIST_SLOT_SUCCESS`;
export const GET_LIST_SLOT_FAILED = `${MANAGER_KEY}/GET_LIST_SLOT_FAILED`;
export const REMOVE_SLOT_FROM_STATE = `${ADMIN_KEY}/REMOVE_SLOT_FROM_STATE`;

export const CREATE_SLOT = `${MANAGER_KEY}/CREATE_SLOT`;
export const CREATE_SLOT_START = `${MANAGER_KEY}/CREATE_SLOT_START`;
export const CREATE_SLOT_SUCCESS = `${MANAGER_KEY}/CREATE_SLOT_SUCCESS`;
export const CREATE_SLOT_FAILED = `${MANAGER_KEY}/CREATE_SLOT_FAILED`;
export const RESET_CREATE_SLOT_STATE = `${MANAGER_KEY}/RESET_CREATE_SLOT_STATE`;

export const UPDATE_SLOT_INFO = `${MANAGER_KEY}/UPDATE_SLOT_INFO`;
export const UPDATE_SLOT_INFO_START = `${MANAGER_KEY}/UPDATE_SLOT_INFO_START`;
export const UPDATE_SLOT_INFO_SUCCESS = `${MANAGER_KEY}/UPDATE_SLOT_INFO_SUCCESS`;
export const UPDATE_SLOT_INFO_FAILED = `${MANAGER_KEY}/UPDATE_SLOT_INFO_FAILED`;

// + schedule

export const GET_LIST_SCHEDULES = `${MANAGER_KEY}/GET_LIST_SCHEDULES`;
export const GET_LIST_SCHEDULES_START = `${MANAGER_KEY}/GET_LIST_SCHEDULES_START`;
export const GET_LIST_SCHEDULES_SUCCESS = `${MANAGER_KEY}/GET_LIST_SCHEDULES_SUCCESS`;
export const GET_LIST_SCHEDULES_FAILED = `${MANAGER_KEY}/GET_LIST_SCHEDULES_FAILED`;

export const CREATE_NEW_SCHEDULE = `${MANAGER_KEY}/CREATE_NEW_SCHEDULE`;
export const CREATE_NEW_SCHEDULE_START = `${MANAGER_KEY}/CREATE_NEW_SCHEDULE_START`;
export const CREATE_NEW_SCHEDULE_SUCCESS = `${MANAGER_KEY}/CREATE_NEW_SCHEDULE_SUCCESS`;
export const CREATE_NEW_SCHEDULE_FAILED = `${MANAGER_KEY}/CREATE_NEW_SCHEDULE_FAILED`;

export const GET_SCHEDULE_DETAIL = `${MANAGER_KEY}/GET_SCHEDULE_DETAIL`;
export const GET_SCHEDULE_DETAIL_START = `${MANAGER_KEY}/GET_SCHEDULE_DETAIL_START`;
export const GET_SCHEDULE_DETAIL_SUCCESS = `${MANAGER_KEY}/GET_SCHEDULE_DETAIL_SUCCESS`;
export const GET_SCHEDULE_DETAIL_FAILED = `${MANAGER_KEY}/GET_SCHEDULE_DETAIL_FAILED`;

export const UPDATE_SCHEDULE_INFO = `${MANAGER_KEY}/UPDATE_SCHEDULE_INFO`;
export const UPDATE_SCHEDULE_INFO_START = `${MANAGER_KEY}/UPDATE_SCHEDULE_INFO_START`;
export const UPDATE_SCHEDULE_INFO_SUCCESS = `${MANAGER_KEY}/UPDATE_SCHEDULE_INFO_SUCCESS`;
export const UPDATE_SCHEDULE_INFO_FAILED = `${MANAGER_KEY}/UPDATE_SCHEDULE_INFO_FAILED`;

export const DELETE_SCHEDULE = `${MANAGER_KEY}/DELETE_SCHEDULE`;
export const DELETE_SCHEDULE_START = `${MANAGER_KEY}/DELETE_SCHEDULE_START`;
export const DELETE_SCHEDULE_SUCCESS = `${MANAGER_KEY}/DELETE_SCHEDULE_SUCCESS`;
export const DELETE_SCHEDULE_FAILED = `${MANAGER_KEY}/DELETE_SCHEDULE_FAILED`;

//  global

const GLOBAL_KEY = "GLOBAL";

export const G_GET_LIST_CURRENT_FILM = `${GLOBAL_KEY}/G_GET_LIST_CURRENT_FILM`;
export const G_GET_LIST_CURRENT_FILM_START = `${GLOBAL_KEY}/G_GET_LIST_CURRENT_FILM_START`;
export const G_GET_LIST_CURRENT_FILM_SUCCESS = `${GLOBAL_KEY}/G_GET_LIST_CURRENT_FILM_SUCCESS`;
export const G_GET_LIST_CURRENT_FILM_FAILED = `${GLOBAL_KEY}/G_GET_LIST_CURRENT_FILM_FAILED`;

export const G_GET_LIST_COMING_FILM = `${GLOBAL_KEY}/G_GET_LIST_COMING_FILM`;
export const G_GET_LIST_COMING_FILM_START = `${GLOBAL_KEY}/G_GET_LIST_COMING_FILM_START`;
export const G_GET_LIST_COMING_FILM_SUCCESS = `${GLOBAL_KEY}/G_GET_LIST_COMING_FILM_SUCCESS`;
export const G_GET_LIST_COMING_FILM_FAILED = `${GLOBAL_KEY}/G_GET_LIST_COMING_FILM_FAILED`;
