/** @format */

//  auth

const AUTH_KEY = "AUTH";

export const LOGIN = `${AUTH_KEY}/LOGIN`;
export const LOGIN_START = `${AUTH_KEY}/LOGIN_START`;
export const LOGIN_SUCCESS = `${AUTH_KEY}/LOGIN_SUCCESS`;
export const LOGIN_FAILED = `${AUTH_KEY}/LOGIN_FAILED`;

export const SIGN_UP = `${AUTH_KEY}/SIGN_UP`;
export const SIGN_UP_START = `${AUTH_KEY}/SIGN_UP_START`;
export const SIGN_UP_SUCCESS = `${AUTH_KEY}/SIGN_UP_SUCCESS`;
export const SIGN_UP_FAILED = `${AUTH_KEY}/SIGN_UP_FAILED`;

export const LOGOUT = `${AUTH_KEY}/LOGOUT`;

// ui
const UI_KEY = "UI";

export const ADD_NOTI = `${UI_KEY}/ADD_NOTI`;
export const REMOVE_NOTI = `${UI_KEY}/REMOVE_NOTI`;

// user

const USER_KEY = "USER";

export const GET_USER_PROFILE = `${USER_KEY}/GET_USER_PROFILE`;
export const GET_USER_PROFILE_START = `${USER_KEY}/GET_USER_PROFILE_START`;
export const GET_USER_PROFILE_SUCCESS = `${USER_KEY}/GET_USER_PROFILE_SUCCESS`;
export const GET_USER_PROFILE_FAILED = `${USER_KEY}/GET_USER_PROFILE_FAILED`;

export const EDIT_USER_PROFILE = `${USER_KEY}/EDIT_USER_PROFILE`;
export const EDIT_USER_PROFILE_START = `${USER_KEY}/EDIT_USER_PROFILE_START`;
export const EDIT_USER_PROFILE_SUCCESS = `${USER_KEY}/EDIT_USER_PROFILE_SUCCESS`;
export const EDIT_USER_PROFILE_FAILED = `${USER_KEY}/EDIT_USER_PROFILE_FAILED`;

// admin

const ADMIN_KEY = "ADMIN";

export const GET_LIST_MANAGER = `${ADMIN_KEY}/GET_LIST_MANAGER`;
export const GET_LIST_MANAGER_START = `${ADMIN_KEY}/GET_LIST_MANAGER_START`;
export const GET_LIST_MANAGER_SUCCESS = `${ADMIN_KEY}/GET_LIST_MANAGER_SUCCESS`;
export const GET_LIST_MANAGER_FAILED = `${ADMIN_KEY}/GET_LIST_MANAGER_FAILED`;

export const GET_LIST_STAFF = `${ADMIN_KEY}/GET_LIST_STAFF`;
export const GET_LIST_STAFF_START = `${ADMIN_KEY}/GET_LIST_STAFF_START`;
export const GET_LIST_STAFF_SUCCESS = `${ADMIN_KEY}/GET_LIST_STAFF_SUCCESS`;
export const GET_LIST_STAFF_FAILED = `${ADMIN_KEY}/GET_LIST_STAFF_FAILED`;

export const CREATE_ACCOUNT = `${ADMIN_KEY}/CREATE_ACCOUNT`;
export const CREATE_ACCOUNT_START = `${ADMIN_KEY}/CREATE_ACCOUNT_START`;
export const CREATE_ACCOUNT_SUCCESS = `${ADMIN_KEY}/CREATE_ACCOUNT_SUCCESS`;
export const CREATE_ACCOUNT_FAILED = `${ADMIN_KEY}/CREATE_ACCOUNT_FAILED`;
export const RESET_CREATE_ACCOUNT_STATE = `${ADMIN_KEY}/RESET_CREATE_ACCOUNT_STATE`;
export const REMOVE_ACCOUNT_FROM_STATE = `${ADMIN_KEY}/REMOVE_ACCOUNT_FROM_STATE`;

export const UPDATE_ACCOUNT_INFO = `${ADMIN_KEY} UPDATE_ACCOUNT_INFO`;
export const UPDATE_ACCOUNT_INFO_START = `${ADMIN_KEY} UPDATE_ACCOUNT_INFO_START`;
export const UPDATE_ACCOUNT_INFO_SUCCESS = `${ADMIN_KEY} UPDATE_ACCOUNT_INFO_SUCCESS`;
export const UPDATE_ACCOUNT_INFO_FAILED = `${ADMIN_KEY} UPDATE_ACCOUNT_INFO_FAILED`;
