//  auth

const AUTH_KEY = "AUTH";

export const LOGIN = `${AUTH_KEY}/LOGIN`;
export const LOGIN_START = `${AUTH_KEY}/LOGIN_START`;
export const LOGIN_SUCCESS = `${AUTH_KEY}/LOGIN_SUCCESS`;
export const LOGIN_FAILED = `${AUTH_KEY}/LOGIN_FAILED`;

export const SIGN_UP = `${AUTH_KEY}/SIGN_UP`;
export const SIGN_UP_START = `${AUTH_KEY}/SIGN_UP_START`;
export const SIGN_UP_SUCCESS = `${AUTH_KEY}/SIGN_UP_SUCCESS`;
export const SIGN_UP_FAILED = `${AUTH_KEY}/SIGN_UP_FAILED`;

export const LOGOUT = `${AUTH_KEY}/LOGOUT`;

// ui
const UI_KEY = "UI";

export const ADD_NOTI = `${UI_KEY}/ADD_NOTI`;
export const REMOVE_NOTI = `${UI_KEY}/REMOVE_NOTI`;

// user

const USER_KEY = "USER";

export const GET_USER_PROFILE = `${USER_KEY}/GET_USER_PROFILE`;
export const GET_USER_PROFILE_START = `${USER_KEY}/GET_USER_PROFILE_START`;
export const GET_USER_PROFILE_SUCCESS = `${USER_KEY}/GET_USER_PROFILE_SUCCESS`;
export const GET_USER_PROFILE_FAILED = `${USER_KEY}/GET_USER_PROFILE_FAILED`;

export const EDIT_USER_PROFILE = `${USER_KEY}/EDIT_USER_PROFILE`;
export const EDIT_USER_PROFILE_START = `${USER_KEY}/EDIT_USER_PROFILE_START`;
export const EDIT_USER_PROFILE_SUCCESS = `${USER_KEY}/EDIT_USER_PROFILE_SUCCESS`;
export const EDIT_USER_PROFILE_FAILED = `${USER_KEY}/EDIT_USER_PROFILE_FAILED`;
